# Site settings

title: Codependent - Founders and Coders Team

description: > # this means to ignore newlines until "baseurl:"
  Find out who we are and see our work at Founders and Coders.

baseurl: ""

url: "http://codependentfc.github.io"  

# gems:
#   - jemoji

# Build settings
markdown: kramdown
